version: "3.9"
name: postgres
services:
  demo-project-pg:
    image: postgres:16.2-alpine3.19
    ports:
      - "5432:5432"
    volumes:
      - ~/dev/db/demo_project:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: demo_project
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres