name: Project Unit Tests

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
      - uses: actions/checkout@v4
      - name: Unit Tests with Gradle
        run: ./gradlew clean test